name: Pytest CI/CD
on: [push]
jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev --locked

      - name: Run pytest
        run: uv run pytest --ignore=test/availability

      - name: Generate badge
        run: |
          uv run genbadge tests -i junit.xml -o pytest.svg
          uv run genbadge coverage -i coverage.xml -o coverage.svg

      - name: Upload test badge
        uses: actions/upload-artifact@v4
        with:
          name: pytest
          path: pytest.svg
          overwrite: true

      - name: Upload coverage badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.svg
          overwrite: true


  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync --dev --locked

      - name: Lint with flake8
        run: |
          uv run flake8 --exit-zero --output-file flake8.txt

      - name: Generate badge
        run: |
          uv run genbadge flake8 -i flake8.txt -o flake8.svg

      - name: Upload badge
        uses: actions/upload-artifact@v4
        with:
          name: flake8
          path: flake8.svg
          overwrite: true
